SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
STARTING_LIFE_COUNT = 3
EXTRA_LIFE_SCORE = 5000
BASE_SCORE = 10
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_INVULNERABILITY_SECONDS = 3.0
ASTEROID_VELOCITIY_MULTIPLIERS = {
    "white": 1.5,
    "yellow": 2.0,
    "orange": 2.5,
    "red": 3.0,
    "green": 3.5,
    "gray": 4.0
}